### ISSUE TITLE
'Large' email templates don't return HTML

### ISSUE THREAD

**Issue by LoveridgeAdestra** [EDMdesigner/email-html-generator-issues#9]
One of our clients has been creating an email campaign in our system using the EDM API but they are having problems. It seems that the length of the email is causing the EDM API to return errors and we don't get any HTML back.

I've attached the template JSON to this ticket.
[56fbbdd98c2ef84e0b8b4ea6.json.txt](https://github.com/EDMdesigner/email-html-generator-issues/files/197483/56fbbdd98c2ef84e0b8b4ea6.json.txt)

Below is the error message we’re getting back:

```
PayloadTooLargeError: too many parameters
   at queryparse (/home/ubuntu/deployments/2016-03-11_5-55-04/eml-generator-service/node_modules/body-parser/lib/types/urlencoded.js:144:13)
   at parse (/home/ubuntu/deployments/2016-03-11_5-55-04/eml-generator-service/node_modules/body-parser/lib/types/urlencoded.js:75:9)
   at /home/ubuntu/deployments/2016-03-11_5-55-04/eml-generator-service/node_modules/body-parser/lib/read.js:108:18
   at invokeCallback (/home/ubuntu/deployments/2016-03-11_5-55-04/eml-generator-service/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
   at done (/home/ubuntu/deployments/2016-03-11_5-55-04/eml-generator-service/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
   at IncomingMessage.onEnd (/home/ubuntu/deployments/2016-03-11_5-55-04/eml-generator-service/node_modules/body-parser/node_modules/raw-body/index.js:308:7)
   at IncomingMessage.EventEmitter.emit (events.js:92:17)
   at _stream_readable.js:920:16
   at process._tickCallback (node.js:415:13) 
```

**Comment by gyulanemeth** [comment]
Hello,

if you change the content type of the request to "application/json", then it should be okay. Also, the payload of the request will be much smaller.

I hope it will solve your problem.

**Comment by gyulanemeth** [comment]
Hello, have you tried to set the content type of the request to application/json?
